pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r images .public
    - cp -r styles .public
    - cp index.html .public
    - rm -rf public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
      - master